language: java
jdk:
  - oraclejdk8

dist: trusty
sudo: false
env:
  global:
    - secure: "CGARY5VWjqCJZXU5ZcisSyvZpvE/ZWPu806WVK2nlDRqHhp17W1UgXTwmuXPtFDut8uv4VcKTrPB8uPqJAQ9iPOCTPHKzRdzOuZr6+2VClBi2rcJkNUpG44ABm4bYnN7QD9clQU7PQr/5JLjzI5G0BEonvJu8IYgAz67+c206HF5vPx6PQKrOEOtcMpoXBkuT9xpFw7wJSXkUiyzWZMuxUPosOapWOrzAdR44Amsl0XKvZkaJDQRAaXn8rAEKkhwbChMLp8bvm4qx5gv1Oyu38Vf/qdmMQaL/c9V1EWec3qle3P8VdWv19xq8VLSKqXB+znNjLyu8GmUa8A6zdQiSNtVJ6z7Q9vaTo/k1a3zt1m+LBeShAsx3MSSxh6zT7CyjJk5Lxi1TJEQh3bTaAO1e1Cqf2gbkeCRoFO0z2VlsN/qF173Q4PlA5yO5iD31jOXaGPHtMNTNb65PB6tXAuJA4SoIElf8et3Jrxkp+0EwA+sl3qNV7PsFVN6iS8+W5aYGf2/xR5yox/o8x6Gj9rbSPLHHhKTiEg42RCbHlN7iOl0hBDlR6P+As/QIpZ/dXs8l4+hi+ojcFgx+z3mQxJYy27ou3jYft8i3axngRPuFG0OsDfqmFFSHXi5it1duXhayiHifGW5xSNr8kAFMSflesUAhkTQO3R9w2Q0NQIY8XQ="
    - secure: "JjHJ9x5jV8duuWitxQg+odPNgkcW1/e0klShCLlRnYlEZbvbe44VCeWwpUAFF358guJrRj4TYAbPbpnLqjzYxWK3NGdcb7UKsKJYm90Y+cTo/MqnMe3jZaAwbquv8ZXhI6emRBgsE3VR4HHldoQpGQ2BP30IHsyHi2IT35xB8WQbX9XEmql3ZdxVUt+Eh59+nw/nv6V7Cu3UuFGwtrOoDuua9NHn0oxqh89pvkyQ3BlSBqc9aKr41b0IDWx6s/8+qJQSs6TF5HpUjgG8CuSP5RRehvsKjJngL0U8chvYx+Z25ko1rvMJrFDCOdzJ1f/WaZTWM+fAIXdvl0tObzPs+VK3DvZ3paJA+XhblytWCX/mN2y7l0dujoxGFFhOlvu4ygsCB4QhYPVk3fIwdf828QfBt5ALHGA1Q2dj8o+vlGfml+gG7fe8h1IqGw5oF+ZEnICEC+8M8cmrKossi6AUpqwDQ6nsI4LsrvXFk4c+2fvJ/QGHVv4yLdSC0DZL4HfWb+EXLJAywhkBLZwJyHPVWnAn7LoPeN4haXqWHdOO6wK9sez66Burw+r6b/zdcKtinlOw7dPb5GXMydVKQe6G/4S3yD8d7h1slZDAvwaof8dh79lluHZD2v6BtGV8ef6F+8e8D0EpAbcyIt7FxnwnQ9CKgLzbtfJ56/bsJyitdtc="

install: true
script: ./.travis.sh

notifications:
  email: false