language: java
jdk:
  - oraclejdk8

dist: trusty
sudo: false
env:
  global:
    - secure: "NgUbPqB2py2G1aUBs9T7AIfQWbMorn9hVOoAHsTQeL9zksorV50W+DvNVppDzxJOCw2FAqGOu9r4Rb4D4x2o9xHlsUhnmDgJScqfzeG/Y+tEpJdB4madVq+QKmKDyBWmewKE+HZIB8weCWA1BWDkvFF4e5AycOu9RU2s3bopB8ZVmiqYWSliDK4JIypMZ9EoTSTinNV6J3MhPtuiasjHWhVIqOHlWDlOre27Bv3d9+lj15yHYj5+RxuuE7u3hRroPqO8f1Pch4qTWAFWKWjl8b10WbCedNI/OgQmBODeS6FR+ZyMHPGD0aGfqhw+LR4O6q2Q1oXk1M7m2CSpGFS/ja3UothLVK2OrqGZ+IcDyewiKorw6BSUUii5H0NDJHvbJUHld9wJCnjGqMsUtFoWmPX7XlrwUhRMOxz5KGXGB67Y9XUEtmnOyCenhmg4tQqri1y21jmv7RxmkSbqzBE75+4XgK8N98lv18BbSqo0/5YPS6noFJhzFavuu7FeS37SZKdja5zondWvzwaXo7tPtfmSytkVk6KNiJFKgkkQd6z1qxFc4aAVGhXgbOUF3WL/ZObrJ0jagDlxbRcgSeOR4m3gcRpu7Wr6e9pUZPscyj1O0NVz9NZecM5y6asHjKlzjJBrNCoLePHW94h2E9SyPzmujp7YTQ5rMkF4oqmy7JU="
    - secure: "O6Bef4+b2JjcfBl94mFlJ6eUaj77F19Bf+/jPCrPsSta6qz9QDuTWNirCmxPgPOi56J8mqHGzcZs7CFPBEW/JnMXfOuzwqKj/jKxYOKm54HsrJqDIGl38ZG0HDqdR40xG9D9oENOd1ZMSt1OJvxA+CZLOhz7oMVaD0kRcqB0KQUKEo1El4Ae7Yf3fvQLsD86XGs9YzGlpjpiWSACizViLPQrqZekA2AD2yAEca4a2PP2NoP9LyznQzmpkGfZt4Pji9Guvn2bV8Fl5W62PxhKefKojgHVSSYzcmxkJI75C8h99tkgqeq4+qQKr1L+tDb3Jd6G1/lIy/E4wpOyl73XGK1djCwzQR2FgNk7ejKsVq66FcWR1P+vn6VjDBVJZQmer1oX1vCNha9egHBW/FH0XE88HqtHhHP3Rcg4a239LOdsJHKz38paJiiNMnv1+zsBFYS3dYC9qLxOouwRNA96aidhg7UIdXq7gEuhynyW00SavG9tKiA45MwmCsq1Cv9JfXAI4wCCA0o5kpPwPyQRqsMHTlkttKCCKs3dbH1lOfhGaC7ajf7FYSez9kryeR+KKNOFsPbkpzszQUMx6f7ziwY3tn1oJ9jzdQeUWGsJGrfPy2dGXygIPgp6+y0ezujbnGjvDmQ3PzXzCfJntc6xFc/zv8hyLHZNlVBlKlNEG20="

install: true
script: ./.travis.sh

notifications:
  email: false