language: java
jdk:
  - oraclejdk8

dist: trusty
sudo: false
env:
  global:
    - secure: "NgUbPqB2py2G1aUBs9T7AIfQWbMorn9hVOoAHsTQeL9zksorV50W+DvNVppDzxJOCw2FAqGOu9r4Rb4D4x2o9xHlsUhnmDgJScqfzeG/Y+tEpJdB4madVq+QKmKDyBWmewKE+HZIB8weCWA1BWDkvFF4e5AycOu9RU2s3bopB8ZVmiqYWSliDK4JIypMZ9EoTSTinNV6J3MhPtuiasjHWhVIqOHlWDlOre27Bv3d9+lj15yHYj5+RxuuE7u3hRroPqO8f1Pch4qTWAFWKWjl8b10WbCedNI/OgQmBODeS6FR+ZyMHPGD0aGfqhw+LR4O6q2Q1oXk1M7m2CSpGFS/ja3UothLVK2OrqGZ+IcDyewiKorw6BSUUii5H0NDJHvbJUHld9wJCnjGqMsUtFoWmPX7XlrwUhRMOxz5KGXGB67Y9XUEtmnOyCenhmg4tQqri1y21jmv7RxmkSbqzBE75+4XgK8N98lv18BbSqo0/5YPS6noFJhzFavuu7FeS37SZKdja5zondWvzwaXo7tPtfmSytkVk6KNiJFKgkkQd6z1qxFc4aAVGhXgbOUF3WL/ZObrJ0jagDlxbRcgSeOR4m3gcRpu7Wr6e9pUZPscyj1O0NVz9NZecM5y6asHjKlzjJBrNCoLePHW94h2E9SyPzmujp7YTQ5rMkF4oqmy7JU="
    - secure: "C2PFwLExT9VmsyY6J+9icefhnn2p3Py290HRBHSJG05zSekKsc32NNiDe1Nw0R6+4KSAO0E0IF+jbQhe6wSGobqLYcgYwN25czVGRrA9hlt+1o0A66ZeXgxNb5rdmRxU8SslieJxsImV68ChKUBkPqUZNMBCbpGQ4/MJq7RgZ1cMXVs3HdnqueI8R2jPLFAa9r5GomqjVOX5pECuBSJpECU8hKMyRFuZIgRQM+1EphxE0cCjgJIhOCvRY/zq8I+Ti2ayHUk/mJWC0ViT8fgYytORnCg34ZrDBLCxJnJoxmQtMB9IBt68C8sPskbaauAqWwUpbcFTRwN/8nK8kAsIKRvC2f7FKg2CYqz5MUI1swIuQvGKQxxs0wub2IrHr8ExsjpkDfwq3eIrf67qSaMWsADZ0fn7p+OG45nB8yQxf1mYhj0Rdyc1h2CntulyJqg9TTxevNSFCQJaBLArxWmVkUx50Gf5WGqKdf3TySh2+iVMnxFidY6iTF8158NzUX4qGvQCoFYEc3iAfpEjTnY+Swy4tJsBEvEhJwrhMBiw/wYJdpMya8Cc03msaMjyGU8BDelOWMe+g7vCs6T+7/33LRtaXHtFt8Baf6ZJNbkN+ebQHWtXuAb0k07FvdUxwoQcN3dow0CbvClMb7agoexyDIogx0q+b7KcWCy9sq3bReQ="

install: true
script: ./.travis.sh

notifications:
  email: false